-- 30 popular European clubs. logo_path matches files in public/club_logos/.
insert into clubs (name, country, logo_path) values
  ('Manchester United',  'England',     'england_manchester-united_512x512.football-logos.cc.png'),
  ('Manchester City',    'England',     'england_manchester-city_512x512.football-logos.cc.png'),
  ('Liverpool',          'England',     'england_liverpool_512x512.football-logos.cc.png'),
  ('Arsenal',            'England',     'england_arsenal_512x512.football-logos.cc.png'),
  ('Chelsea',            'England',     'england_chelsea_512x512.football-logos.cc.png'),
  ('Tottenham Hotspur',  'England',     'england_tottenham_512x512.football-logos.cc.png'),
  ('Newcastle United',   'England',     'england_newcastle_512x512.football-logos.cc.png'),
  ('Real Madrid',        'Spain',       'spain_real-madrid_512x512.football-logos.cc.png'),
  ('Barcelona',          'Spain',       'spain_barcelona_512x512.football-logos.cc.png'),
  ('Atlético Madrid',    'Spain',       'spain_atletico-madrid_512x512.football-logos.cc.png'),
  ('Sevilla',            'Spain',       'spain_sevilla_512x512.football-logos.cc.png'),
  ('Juventus',           'Italy',       'italy_juventus_512x512.football-logos.cc.png'),
  ('AC Milan',           'Italy',       'italy_milan_512x512.football-logos.cc.png'),
  ('Inter Milan',        'Italy',       'italy_inter_512x512.football-logos.cc.png'),
  ('Napoli',             'Italy',       'italy_napoli_512x512.football-logos.cc.png'),
  ('AS Roma',            'Italy',       'italy_roma_512x512.football-logos.cc.png'),
  ('Lazio',              'Italy',       'italy_lazio_512x512.football-logos.cc.png'),
  ('Bayern Munich',      'Germany',     'germany_bayern-munchen_512x512.football-logos.cc.png'),
  ('Borussia Dortmund',  'Germany',     'germany_borussia-dortmund_512x512.football-logos.cc.png'),
  ('Bayer Leverkusen',   'Germany',     'germany_bayer-leverkusen_512x512.football-logos.cc.png'),
  ('RB Leipzig',         'Germany',     'germany_rb-leipzig_512x512.football-logos.cc.png'),
  ('Paris Saint-Germain','France',      'france_paris-saint-germain_512x512.football-logos.cc.png'),
  ('Marseille',          'France',      'france_marseille_512x512.football-logos.cc.png'),
  ('AS Monaco',          'France',      'france_as-monaco_512x512.football-logos.cc.png'),
  ('Lyon',               'France',      'france_lyon_512x512.football-logos.cc.png'),
  ('Benfica',            'Portugal',    'portugal_benfica_512x512.football-logos.cc.png'),
  ('FC Porto',           'Portugal',    'portugal_fc-porto_512x512.football-logos.cc.png'),
  ('Sporting CP',        'Portugal',    'portugal_sporting-cp_512x512.football-logos.cc.png'),
  ('Ajax',               'Netherlands', 'netherlands_ajax_512x512.football-logos.cc.png'),
  ('PSV Eindhoven',      'Netherlands', 'netherlands_psv_512x512.football-logos.cc.png')
on conflict (name) do nothing;
