// The 100 best players of 2026 — single source of truth for the photo
// download script and the DB seeding script.
// Each entry: [rank, name (display), search (ASCII name for TheSportsDB), position, country, club]

export const PLAYERS = [
  [1, "Ousmane Dembélé", "Ousmane Dembele", "FW", "France", "Paris Saint-Germain"],
  [2, "Lamine Yamal", "Lamine Yamal", "FW", "Spain", "Barcelona"],
  [3, "Vitinha", "Vitinha", "MF", "Portugal", "Paris Saint-Germain"],
  [4, "Mohamed Salah", "Mohamed Salah", "FW", "Egypt", "Liverpool"],
  [5, "Raphinha", "Raphinha", "FW", "Brazil", "Barcelona"],
  [6, "Achraf Hakimi", "Achraf Hakimi", "DF", "Morocco", "Paris Saint-Germain"],
  [7, "Kylian Mbappé", "Kylian Mbappe", "FW", "France", "Real Madrid"],
  [8, "Cole Palmer", "Cole Palmer", "MF", "England", "Chelsea"],
  [9, "Gianluigi Donnarumma", "Gianluigi Donnarumma", "GK", "Italy", "Manchester City"],
  [10, "Nuno Mendes", "Nuno Mendes", "DF", "Portugal", "Paris Saint-Germain"],
  [11, "Pedri", "Pedri", "MF", "Spain", "Barcelona"],
  [12, "Khvicha Kvaratskhelia", "Khvicha Kvaratskhelia", "FW", "Georgia", "Paris Saint-Germain"],
  [13, "Erling Haaland", "Erling Haaland", "FW", "Norway", "Manchester City"],
  [14, "Désiré Doué", "Desire Doue", "FW", "France", "Paris Saint-Germain"],
  [15, "Viktor Gyökeres", "Viktor Gyokeres", "FW", "Sweden", "Arsenal"],
  [16, "Vinícius Júnior", "Vinicius Junior", "FW", "Brazil", "Real Madrid"],
  [17, "Jude Bellingham", "Jude Bellingham", "MF", "England", "Real Madrid"],
  [18, "Florian Wirtz", "Florian Wirtz", "MF", "Germany", "Liverpool"],
  [19, "João Neves", "Joao Neves", "MF", "Portugal", "Paris Saint-Germain"],
  [20, "Lautaro Martínez", "Lautaro Martinez", "FW", "Argentina", "Inter Milan"],
  [21, "Robert Lewandowski", "Robert Lewandowski", "FW", "Poland", "Barcelona"],
  [22, "Alexis Mac Allister", "Alexis Mac Allister", "MF", "Argentina", "Liverpool"],
  [23, "Serhou Guirassy", "Serhou Guirassy", "FW", "Guinea", "Borussia Dortmund"],
  [24, "Harry Kane", "Harry Kane", "FW", "England", "Bayern Munich"],
  [25, "Declan Rice", "Declan Rice", "MF", "England", "Arsenal"],
  [26, "Rodri", "Rodri", "MF", "Spain", "Manchester City"],
  [27, "Michael Olise", "Michael Olise", "FW", "France", "Bayern Munich"],
  [28, "Scott McTominay", "Scott McTominay", "MF", "Scotland", "Napoli"],
  [29, "Fabián Ruiz", "Fabian Ruiz", "MF", "Spain", "Paris Saint-Germain"],
  [30, "Denzel Dumfries", "Denzel Dumfries", "DF", "Netherlands", "Inter Milan"],
  [31, "Virgil van Dijk", "Virgil van Dijk", "DF", "Netherlands", "Liverpool"],
  [32, "Bukayo Saka", "Bukayo Saka", "FW", "England", "Arsenal"],
  [33, "Alexander Isak", "Alexander Isak", "FW", "Sweden", "Liverpool"],
  [34, "Martin Ødegaard", "Martin Odegaard", "MF", "Norway", "Arsenal"],
  [35, "Federico Valverde", "Federico Valverde", "MF", "Uruguay", "Real Madrid"],
  [36, "Thibaut Courtois", "Thibaut Courtois", "GK", "Belgium", "Real Madrid"],
  [37, "Julián Álvarez", "Julian Alvarez", "FW", "Argentina", "Atlético Madrid"],
  [38, "Jamal Musiala", "Jamal Musiala", "MF", "Germany", "Bayern Munich"],
  [39, "Phil Foden", "Phil Foden", "MF", "England", "Manchester City"],
  [40, "William Saliba", "William Saliba", "DF", "France", "Arsenal"],
  [41, "Marquinhos", "Marquinhos", "DF", "Brazil", "Paris Saint-Germain"],
  [42, "Antoine Griezmann", "Antoine Griezmann", "FW", "France", "Atlético Madrid"],
  [43, "Bruno Fernandes", "Bruno Fernandes", "MF", "Portugal", "Manchester United"],
  [44, "Marcus Thuram", "Marcus Thuram", "FW", "France", "Inter Milan"],
  [45, "Victor Osimhen", "Victor Osimhen", "FW", "Nigeria", "Galatasaray"],
  [46, "Rafael Leão", "Rafael Leao", "FW", "Portugal", "AC Milan"],
  [47, "Alisson Becker", "Alisson Becker", "GK", "Brazil", "Liverpool"],
  [48, "Trent Alexander-Arnold", "Trent Alexander-Arnold", "DF", "England", "Real Madrid"],
  [49, "Joshua Kimmich", "Joshua Kimmich", "MF", "Germany", "Bayern Munich"],
  [50, "Rúben Dias", "Ruben Dias", "DF", "Portugal", "Manchester City"],
  [51, "Gabriel Magalhães", "Gabriel Magalhaes", "DF", "Brazil", "Arsenal"],
  [52, "Antonio Rüdiger", "Antonio Rudiger", "DF", "Germany", "Real Madrid"],
  [53, "Ibrahima Konaté", "Ibrahima Konate", "DF", "France", "Liverpool"],
  [54, "Joško Gvardiol", "Josko Gvardiol", "DF", "Croatia", "Manchester City"],
  [55, "Jan Oblak", "Jan Oblak", "GK", "Slovenia", "Atlético Madrid"],
  [56, "Nicolò Barella", "Nicolo Barella", "MF", "Italy", "Inter Milan"],
  [57, "Hakan Çalhanoğlu", "Hakan Calhanoglu", "MF", "Turkey", "Inter Milan"],
  [58, "Tijjani Reijnders", "Tijjani Reijnders", "MF", "Netherlands", "Manchester City"],
  [59, "Moisés Caicedo", "Moises Caicedo", "MF", "Ecuador", "Chelsea"],
  [60, "Enzo Fernández", "Enzo Fernandez", "MF", "Argentina", "Chelsea"],
  [61, "Dominik Szoboszlai", "Dominik Szoboszlai", "MF", "Hungary", "Liverpool"],
  [62, "Ryan Gravenberch", "Ryan Gravenberch", "MF", "Netherlands", "Liverpool"],
  [63, "Aurélien Tchouaméni", "Aurelien Tchouameni", "MF", "France", "Real Madrid"],
  [64, "Eduardo Camavinga", "Eduardo Camavinga", "MF", "France", "Real Madrid"],
  [65, "Frenkie de Jong", "Frenkie de Jong", "MF", "Netherlands", "Barcelona"],
  [66, "Martín Zubimendi", "Martin Zubimendi", "MF", "Spain", "Arsenal"],
  [67, "Bernardo Silva", "Bernardo Silva", "MF", "Portugal", "Manchester City"],
  [68, "Pau Cubarsí", "Pau Cubarsi", "DF", "Spain", "Barcelona"],
  [69, "Jules Koundé", "Jules Kounde", "DF", "France", "Barcelona"],
  [70, "Alejandro Balde", "Alejandro Balde", "DF", "Spain", "Barcelona"],
  [71, "Alessandro Bastoni", "Alessandro Bastoni", "DF", "Italy", "Inter Milan"],
  [72, "Dayot Upamecano", "Dayot Upamecano", "DF", "France", "Bayern Munich"],
  [73, "Kim Min-jae", "Kim Min-Jae", "DF", "South Korea", "Bayern Munich"],
  [74, "Theo Hernández", "Theo Hernandez", "DF", "France", "Al-Hilal"],
  [75, "Éder Militão", "Eder Militao", "DF", "Brazil", "Real Madrid"],
  [76, "Dean Huijsen", "Dean Huijsen", "DF", "Spain", "Real Madrid"],
  [77, "Dani Carvajal", "Dani Carvajal", "DF", "Spain", "Real Madrid"],
  [78, "Jeremie Frimpong", "Jeremie Frimpong", "DF", "Netherlands", "Liverpool"],
  [79, "Willian Pacho", "Willian Pacho", "DF", "Ecuador", "Paris Saint-Germain"],
  [80, "John Stones", "John Stones", "DF", "England", "Manchester City"],
  [81, "Mike Maignan", "Mike Maignan", "GK", "France", "AC Milan"],
  [82, "David Raya", "David Raya", "GK", "Spain", "Arsenal"],
  [83, "Emiliano Martínez", "Emiliano Martinez", "GK", "Argentina", "Aston Villa"],
  [84, "Yann Sommer", "Yann Sommer", "GK", "Switzerland", "Inter Milan"],
  [85, "Joan García", "Joan Garcia", "GK", "Spain", "Barcelona"],
  [86, "Lucas Chevalier", "Lucas Chevalier", "GK", "France", "Paris Saint-Germain"],
  [87, "Bradley Barcola", "Bradley Barcola", "FW", "France", "Paris Saint-Germain"],
  [88, "Nico Williams", "Nico Williams", "FW", "Spain", "Athletic Club"],
  [89, "Rodrygo", "Rodrygo", "FW", "Brazil", "Real Madrid"],
  [90, "Ferran Torres", "Ferran Torres", "FW", "Spain", "Barcelona"],
  [91, "Marcus Rashford", "Marcus Rashford", "FW", "England", "Barcelona"],
  [92, "Christian Pulisic", "Christian Pulisic", "FW", "USA", "AC Milan"],
  [93, "Kenan Yıldız", "Kenan Yıldız", "FW", "Turkey", "Juventus"],
  [94, "Dušan Vlahović", "Dusan Vlahovic", "FW", "Serbia", "Juventus"],
  [95, "Jonathan David", "Jonathan David", "FW", "Canada", "Juventus"],
  [96, "Loïs Openda", "Lois Openda", "FW", "Belgium", "Juventus"],
  [97, "Gabriel Martinelli", "Gabriel Martinelli", "FW", "Brazil", "Arsenal"],
  [98, "Estêvão", "Estevao", "FW", "Brazil", "Chelsea"],
  [99, "Xavi Simons", "Xavi Simons", "MF", "Netherlands", "Tottenham Hotspur"],
  [100, "Gavi", "Gavi", "MF", "Spain", "Barcelona"],
];

export const slugOf = (search) =>
  search
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/ı/g, "i")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
